


from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import UUID
from pydantic import BaseModel, Field, condecimal, conint


# 1. Mirror your PostgreSQL database Enums
class GroupPeriodEnum(str, Enum):
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"


class GroupLifecycleEnum(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


# 2. Base Properties shared across schemas
class SavingsGroupBase(BaseModel):
    group_name: str = Field(..., min_length=3, max_length=100, examples=["Akawo Tech Bros Circle"])
    contribution_amount: condecimal(max_digits=15, decimal_places=2) = Field(
        ..., gt=0, examples=[50000.00]
    )
    cycle_period: GroupPeriodEnum = Field(..., examples=["WEEKLY"])
    max_slots: conint(gt=1, le=100) = Field(..., examples=[10])


# 3. Payload expected from frontend when CREATING a group
class SavingsGroupCreate(SavingsGroupBase):
    # Note: creator_id will be extracted securely from the JWT session token in your route,
    # and nomba_sub_account_id will be generated by your Nomba backend service.
    pass


# 4. Payload used when UPDATING group parameters
class SavingsGroupUpdate(BaseModel):
    group_name: Optional[str] = Field(None, min_length=3, max_length=100)
    status: Optional[GroupLifecycleEnum] = None
    current_cycle_round: Optional[conint(gt=0)] = None


class GroupActivationRequest(BaseModel):
    group_id: UUID


# 5. Schema for database reads / API responses
class SavingsGroupResponse(SavingsGroupBase):
    group_id: UUID
    creator_id: Optional[UUID]
    status: GroupLifecycleEnum
    current_cycle_round: int
    nomba_sub_account_id: str
    group_link: Optional[str] = None
    activated_at: Optional[datetime] = None
    created_at: datetime

    class Config:
        # Allows Pydantic to read database rows or ORM objects automatically
        from_attributes = True


# 6. Advanced: Detailed Response including estimated calculations
class SavingsGroupDetailResponse(SavingsGroupResponse):
    total_pool_per_round: float = Field(
        ..., description="Calculated total cash payout distributed per round"
    )
    estimated_lifecycle_duration_days: int = Field(
        ..., description="Total days required to run this complete Esusu loop"
    )
